/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_topactivity_service_DaemonService */

#ifndef _Included_com_example_administrator_topactivity_service_DaemonService
#define _Included_com_example_administrator_topactivity_service_DaemonService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_administrator_topactivity_service_DaemonService_MSG_HANDLE_CHECK
#define com_example_administrator_topactivity_service_DaemonService_MSG_HANDLE_CHECK 1L
/*
 * Class:     com_example_administrator_topactivity_service_DaemonService
 * Method:    initDaemon
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_topactivity_service_DaemonService_initDaemon
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
