/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_topactivity_service_DaemonService_HandleRun */

#ifndef _Included_com_example_administrator_topactivity_service_DaemonService_HandleRun
#define _Included_com_example_administrator_topactivity_service_DaemonService_HandleRun
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
